//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2005/Atom")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/2005/Atom", IsNullable=false)]
public partial class feed {
    
    private string idField;
    
    private string titleField;
    
    private string updatedField;
    
    private feedEntry[] entryField;
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entry")]
    public feedEntry[] entry {
        get {
            return this.entryField;
        }
        set {
            this.entryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2005/Atom")]
public partial class feedEntry {
    
    private string idField;
    
    private string titleField;
    
    private string publishedField;
    
    private string updatedField;
    
    private feedEntryLink[] linkField;
    
    private feedEntryContent[] contentField;
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string published {
        get {
            return this.publishedField;
        }
        set {
            this.publishedField = value;
        }
    }
    
    /// <remarks/>
    public string updated {
        get {
            return this.updatedField;
        }
        set {
            this.updatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public feedEntryLink[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("content")]
    public feedEntryContent[] content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2005/Atom")]
public partial class feedEntryLink {
    
    private string hrefField;
    
    private string relField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rel {
        get {
            return this.relField;
        }
        set {
            this.relField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2005/Atom")]
public partial class feedEntryContent {
    
    private string meterReadingField;
    
    private IntervalBlock[] intervalBlockField; //Added []
    
    private ReadingType readingTypeField;
    
    private UsagePointServiceCategory[] usagePointField;
    
    private LocalTimeParameters localTimeParametersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://naesb.org/espi")]
    public string MeterReading {
        get {
            return this.meterReadingField;
        }
        set {
            this.meterReadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://naesb.org/espi")]
    public IntervalBlock[] IntervalBlock {                  // added []
        get {
            return this.intervalBlockField;
        }
        set {
            this.intervalBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://naesb.org/espi")]
    public ReadingType ReadingType {
        get {
            return this.readingTypeField;
        }
        set {
            this.readingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://naesb.org/espi")]
    [System.Xml.Serialization.XmlArrayItemAttribute("ServiceCategory", IsNullable=false)]
    public UsagePointServiceCategory[] UsagePoint {
        get {
            return this.usagePointField;
        }
        set {
            this.usagePointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://naesb.org/espi")]
    public LocalTimeParameters LocalTimeParameters {
        get {
            return this.localTimeParametersField;
        }
        set {
            this.localTimeParametersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://naesb.org/espi", IsNullable=false)]
public partial class IntervalBlock {
    
    private IntervalBlockInterval[] intervalField;
    
    private IntervalBlockIntervalReading[] intervalReadingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("interval")]
    public IntervalBlockInterval[] interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IntervalReading")]
    public IntervalBlockIntervalReading[] IntervalReading {
        get {
            return this.intervalReadingField;
        }
        set {
            this.intervalReadingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
public partial class IntervalBlockInterval {
    
    private string durationField;
    
    private string startField;
    
    /// <remarks/>
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
public partial class IntervalBlockIntervalReading {
    
    private string valueField;
    
    private IntervalBlockIntervalReadingTimePeriod[] timePeriodField;
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("timePeriod")]
    public IntervalBlockIntervalReadingTimePeriod[] timePeriod {
        get {
            return this.timePeriodField;
        }
        set {
            this.timePeriodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
public partial class IntervalBlockIntervalReadingTimePeriod {
    
    private string durationField;
    
    private string startField;
    
    /// <remarks/>
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://naesb.org/espi", IsNullable=false)]
public partial class ReadingType {
    
    private string accumulationBehaviourField;
    
    private string commodityField;
    
    private string currencyField;
    
    private string dataQualifierField;
    
    private string defaultQualityField;
    
    private string flowDirectionField;
    
    private string intervalLengthField;
    
    private string kindField;
    
    private string phaseField;
    
    private string powerOfTenMultiplierField;
    
    private string timeAttributeField;
    
    private string uomField;
    
    /// <remarks/>
    public string accumulationBehaviour {
        get {
            return this.accumulationBehaviourField;
        }
        set {
            this.accumulationBehaviourField = value;
        }
    }
    
    /// <remarks/>
    public string commodity {
        get {
            return this.commodityField;
        }
        set {
            this.commodityField = value;
        }
    }
    
    /// <remarks/>
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string dataQualifier {
        get {
            return this.dataQualifierField;
        }
        set {
            this.dataQualifierField = value;
        }
    }
    
    /// <remarks/>
    public string defaultQuality {
        get {
            return this.defaultQualityField;
        }
        set {
            this.defaultQualityField = value;
        }
    }
    
    /// <remarks/>
    public string flowDirection {
        get {
            return this.flowDirectionField;
        }
        set {
            this.flowDirectionField = value;
        }
    }
    
    /// <remarks/>
    public string intervalLength {
        get {
            return this.intervalLengthField;
        }
        set {
            this.intervalLengthField = value;
        }
    }
    
    /// <remarks/>
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    public string phase {
        get {
            return this.phaseField;
        }
        set {
            this.phaseField = value;
        }
    }
    
    /// <remarks/>
    public string powerOfTenMultiplier {
        get {
            return this.powerOfTenMultiplierField;
        }
        set {
            this.powerOfTenMultiplierField = value;
        }
    }
    
    /// <remarks/>
    public string timeAttribute {
        get {
            return this.timeAttributeField;
        }
        set {
            this.timeAttributeField = value;
        }
    }
    
    /// <remarks/>
    public string uom {
        get {
            return this.uomField;
        }
        set {
            this.uomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
public partial class UsagePointServiceCategory {
    
    private string kindField;
    
    /// <remarks/>
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://naesb.org/espi", IsNullable=false)]
public partial class LocalTimeParameters {
    
    private string dstEndRuleField;
    
    private string dstOffsetField;
    
    private string dstStartRuleField;
    
    private string tzOffsetField;
    
    /// <remarks/>
    public string dstEndRule {
        get {
            return this.dstEndRuleField;
        }
        set {
            this.dstEndRuleField = value;
        }
    }
    
    /// <remarks/>
    public string dstOffset {
        get {
            return this.dstOffsetField;
        }
        set {
            this.dstOffsetField = value;
        }
    }
    
    /// <remarks/>
    public string dstStartRule {
        get {
            return this.dstStartRuleField;
        }
        set {
            this.dstStartRuleField = value;
        }
    }
    
    /// <remarks/>
    public string tzOffset {
        get {
            return this.tzOffsetField;
        }
        set {
            this.tzOffsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2005/Atom")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/2005/Atom", IsNullable=false)]
public partial class NewDataSet {
    
    private feed[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("feed")]
    public feed[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://naesb.org/espi")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://naesb.org/espi", IsNullable=false)]
public partial class UsagePoint {
    
    private UsagePointServiceCategory[] serviceCategoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceCategory")]
    public UsagePointServiceCategory[] ServiceCategory {
        get {
            return this.serviceCategoryField;
        }
        set {
            this.serviceCategoryField = value;
        }
    }
}
